export const courses = [
    {
        id : 1,
        name: "Машинное обучение",
        teacher: "Степанов Ю.И.",
        image: "/img/courses/ML.jpg",
        price: 23999,
        direct: "Программирование",
        universityLink: "https://konspekta.net/lektsiiorgimg/baza17/2963545132234.files/image001.jpg",
        university:"КемГУ",
    },
    {
        id : 2,
        name: "Дизайн интерфейсов",
        teacher: "Щеглов П.И.",
        image: "/img/courses/ui-uxDesign.jpg",
        price: 18456,
        direct: "Программирование",
        universityLink: "https://konspekta.net/lektsiiorgimg/baza17/2963545132234.files/image001.jpg",
        university:"КемГУ",
    },
    {
        id : 3,
        name: "Чо",
        teacher: "Щеглов П.И.",
        image: "/img/courses/ui-uxDesign.jpg",
        price: 18456,
        direct: "Программирование",
        universityLink: "https://konspekta.net/lektsiiorgimg/baza17/2963545132234.files/image001.jpg",
        university:"КемГУ",
    },
    {
        id : 4,
        name: "Чо",
        teacher: "Щеглов П.И.",
        image: "/img/courses/ui-uxDesign.jpg",
        price: 18456,
        direct: "Программирование",
        universityLink: "https://konspekta.net/lektsiiorgimg/baza17/2963545132234.files/image001.jpg",
        university:"КемГУ",
    },
    {
        id : 5,
        name: "Чо",
        teacher: "Щеглов П.И.",
        image: "/img/courses/ui-uxDesign.jpg",
        price: 18456,
        direct: "Программирование",
        universityLink: "https://konspekta.net/lektsiiorgimg/baza17/2963545132234.files/image001.jpg",
        university:"КемГУ",
    },
    {
        id : 6,
        name: "Чо",
        teacher: "Щеглов П.И.",
        image: "/img/courses/ui-uxDesign.jpg",
        price: 18456,
        direct: "Программирование",
        universityLink: "https://konspekta.net/lektsiiorgimg/baza17/2963545132234.files/image001.jpg",
        university:"КемГУ",
    },
]